In [17]:
import pandas as pd
data=pd.read_csv('FoodPrice_in_Turkey.csv', encoding="ISO-8859-1")
display(data)

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

In [ ]:
#2. Đổi tên cột thuộc tính

In [18]:
data.rename(columns={'Place':'Địa chỉ','ProductId':'Mã sản phẩm','ProductName':'Tên sản phẩm','UmId':'Số lượng','UmName':'Đơn vị','Month':'Tháng','Year':'Năm','Price':'Giá'},inplace=True)
data

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Số lượng,Đơn vị,Tháng,Năm,Giá
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

In [ ]:
#3. Thêm một cột mới trong DataFrame

In [19]:
# Thêm một cột mới với tất cả các giá trị rỗng NaN
data['new_column']='NaN'
data

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Số lượng,Đơn vị,Tháng,Năm,Giá,new_column
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,NaN
...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,NaN
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,NaN

In [6]:
# Thêm cột giảm giá 10% cho tất cả các bản ghi
data['Giảm giá']='10%'
data

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Số lượng,Đơn vị,Tháng,Năm,Giá,new_column,Giảm giá
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,NaN,10%
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,NaN,10%
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,NaN,10%
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,NaN,10%
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,NaN,10%
...,...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,NaN,10%
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,NaN,10%
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,NaN,10%
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,NaN,10%
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,NaN,10%

In [7]:
# Thêm cột giảm giá 12% cho tất cả các bản ghi
data.insert(10,'GIảm giá 2',pd.Series('12%',index=data.index))
data

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Số lượng,Đơn vị,Tháng,Năm,Giá,new_column,Giảm giá,GIảm giá 2
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,NaN,10%,12%
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,NaN,10%,12%
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,NaN,10%,12%
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,NaN,10%,12%
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,NaN,10%,12%
...,...,...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,NaN,10%,12%
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,NaN,10%,12%
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,NaN,10%,12%
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,NaN,10%,12%
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,NaN,10%,12%

In [13]:
#4. Thêm một dòng mới vào trong DataFrame
data=data.append({'Địa chỉ':'Hà Nội','Mã sản phẩm':'RR','Tên sản phẩm':'Rice','Số lượng':10,'Đơn vị':'KG','Tháng':6,'Năm':2021,'Giá':84.3785,'new_comlumn':'NaN','Giảm giá':'10%','Giảm giá 2':'12%'},ignore_index=True)
data

C:\Users\Asus\AppData\Local\Temp\ipykernel_13648\349770146.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append({'Địa chỉ':'Hà Nội','Mã sản phẩm':'RR','Tên sản phẩm':'Rice','Số lượng':10,'Đơn vị':'KG','Tháng':6,'Năm':2021,'Giá':84.3785,'new_comlumn':'NaN','Giảm giá':'10%','Giảm giá 2':'12%'},ignore_index=True)

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Số lượng,Đơn vị,Tháng,Năm,Giá,Giảm giá,Giảm giá 2,new_comlumn
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,NaN,NaN,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,NaN,NaN,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,NaN,NaN,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,NaN,NaN,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,NaN,NaN,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,NaN,NaN,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,NaN,NaN,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,NaN,NaN,NaN
7381,Hà Nội,RR,Rice,10,KG,6,2021,84.3785,10%,12%,NaN

In [20]:
#5. Xóa một cột trong DataFrame
data1=data
del data1['new_column']
data1

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Số lượng,Đơn vị,Tháng,Năm,Giá
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

In [21]:
## Xóa nhiều cột sử dụng phương thức drop()
data1.drop(['Số lượng','Năm'],axis=1,inplace=True)
data1

,Địa chỉ,Mã sản phẩm,Tên sản phẩm,Đơn vị,Tháng,Giá
0,National Average,52,Rice - Retail,KG,5,4.4920
1,National Average,52,Rice - Retail,KG,6,4.5786
2,National Average,52,Rice - Retail,KG,11,4.7865
3,National Average,52,Rice - Retail,KG,12,5.1337
4,National Average,52,Rice - Retail,KG,1,5.5099
...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,KG,8,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,KG,9,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,KG,10,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,KG,11,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,KG,12,51.6071